services:
  - type: web
    name: edutchad
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build && echo "--- CONTENU DE dist/ ---" && find dist -maxdepth 2
    startCommand: node dist/main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
